#!/bin/bash
#!/usr/bin/env bash
# shellcheck disable=SC2009

PID_FILE="/var/run/myscript.pid"

# PID faylını yaratmaq
echo $$ > "$PID_FILE"

# SIGINT siqnalı üçün funksiyanı təyin et
sigint_handler() {
    echo "Y U no love me?!"
}

# SIGTERM siqnalı üçün funksiyanı təyin et
sigterm_handler() {
    echo "I hate the kill command"
}

# SIGQUIT və SIGTERM üçün proses dayandırma funksiyası
cleanup() {
    rm -f "$PID_FILE"
    exit 0
}

# Siqnalları tutmaq
trap sigint_handler SIGINT
trap sigterm_handler SIGTERM
trap cleanup SIGQUIT SIGTERM

# Sonsuz döngü
while true; do
    echo "To infinity and beyond"
    sleep 2
done
