#!/usr/bin/env bash
# This script kills the 7-highlander process

# Highlander PID tapılır
pid=$(pgrep -f 7-highlander)

# Əgər PID tapılıbsa, prosesi öldürürük
if [ -n "$pid" ]; then
    kill "$pid"
fi
